[global]
    workgroup = WORKGROUP
    server string = Database Server
    security = user
    map to guest = Bad User
    log file = /var/log/samba/%m.log
    max log size = 50
    # Required for CVE-2017-7494
    nt pipe support = yes

[public]
    path = /srv/public
    browseable = yes
    writable = yes
    guest ok = yes
    read only = no
    create mask = 0777
    directory mask = 0777
    force user = root
