import './About.css'
import MethodFigure from './method.png'

/**
 * The about page component
 */
function About() {
  return (
    <div className="About">
      <h2>About</h2>
      <hr />
      <p>
        This is the frontend of a <b>multiagent incident response system</b> that leverages large language
        models (LLMs) to assist security operators during incident handling. The system consists of
        a collection of agents that work together to automate incident response tasks and provide
        insights to security operators. Each agent is designed to perform a specific role in the
        incident response process, such as generating an incident report, orchestrating the
        planning, and generating a response plan. To achieve their goals, the agents interact with
        each other and can invoke a set of <b>tools</b>. In particular, the agents have access to
        the following tools:
        <br />
        <br />
        <ul>
          <li>
            <b>Digital twin terminal.</b> This tool allows agents to execute arbitrary bash commands
            inside a digital twin (i.e., a virtual replica) of the system that was affected by the
            incident.{' '}
          </li>
          <li>
            <b>Threat intelligence APIs and knowledge bases.</b> This tool allows agents to retrieve
            information from external knowledge bases and threat intelligence APIs (e.g., the OTX
            API).{' '}
          </li>
          <li>
            <b>Python sandbox.</b> This tool allows agents to execute arbitrary Python code within a
            sandboxed environment.
          </li>
        </ul>
        The multiagent system includes 12 different types of agents that are organized in a
        hierarchical structure, as illustrated in the figure below. Specifically, the system
        includes the following types of agents:
        <br />
        <br />
        <ol>
          <li>
            <b>Orchestrator</b>: This agent is responsible for orchestrating the incident response
            process.
          </li>
          <li>
            <b>Host analyzer</b>: This agent is responsible for analyzing a specific host of the
            digital twin.
          </li>
          <li>
            <b>Reporter</b>: This agent is responsible for analyzing the digital twin and generating
            an incdient report.
          </li>
          <li>
            <b>Report verifier</b>: This agent is responsible for verifying a report generated by
            the Reporter agent.
          </li>
          <li>
            <b>Report manager</b>: This agent is responsible for coordinating the process of
            generating the incident report. In particular, it decides how many times to revise and
            verify the report.
          </li>
          <li>
            <b>Attack path verifier</b>: This agent is responsible for verifying the attack path in
            the incident report returned by the report manager agent.
          </li>
          <li>
            <b>Code generator</b>: This agent is responsible for generating a code model of the
            process of recovering from the incident.
          </li>
          <li>
            <b>Code verifier</b>: This agent is responsible for verifying the code generated by the
            code generator agent.
          </li>
          <li>
            <b>Code manager</b>: This agent is responsible for coordinating the process of
            generating the code model. In particular, it decides how many times to revise and verify
            the code.
          </li>
          <li>
            <b>Planner</b>: This agent is responsible for computing a response plan based on the
            code model, e.g., through reinforcement learning
          </li>
          <li>
            <b>Plan verifier</b>: This agent is responsible for verifying the plan generated by the
            planner.
          </li>
          <li>
            <b>Plan manager</b>: This agent is responsible for coordinating the process of
            generating the response plan. In particular, it decides how many times to revise and
            verify the plan.
          </li>
        </ol>
      </p>
      <img src={MethodFigure} alt="Method overview" className="method-figure" />
    </div>
  )
}

export default About
