/**
 * File with constants
 */

export const LOGIN_RESOURCE = 'login'
export const ABOUT_RESOURCE = 'about'
export const RESPONSE_PLANNER_RESOURCE = 'response-planner'
export const LLM_RESOURCE = 'llm'
export const NOT_FOUND_RESOURCE = '*'
export const API_BASE_URL = '/api'
export const API_HEALTH_URL = '/api/health'
export const API_PLAN_URL = '/api/plan'
export const API_EXAMPLE_URL = '/api/example'
export const API_LOGIN_URL = '/api/login'
export const API_LLM_URL = '/api/llm'
export const TOOLS_RESOURCE = 'tools'
export const API_TAVILY_URL = '/api/tavily'
export const API_TAVILY_SEARCH_URL = '/api/tavily/search'
export const API_NVD_URL = '/api/nvd'
export const API_NVD_SEARCH_URL = '/api/nvd/search'
export const API_MITRE_URL = '/api/mitre'
export const API_MITRE_SEARCH_URL = '/api/mitre/search'
export const API_VIRUSTOTAL_URL = '/api/virustotal'
export const API_VIRUSTOTAL_SCAN_URL = '/api/virustotal/scan'
export const API_ABUSEIPDB_URL = '/api/abuseipdb'
export const API_ABUSEIPDB_CHECK_URL = '/api/abuseipdb/check'
export const API_OTX_URL = '/api/otx'
export const API_OTX_SEARCH_URL = '/api/otx/search'
export const DIGITAL_TWIN_RESOURCE = 'digital-twin'
export const API_DIGITAL_TWIN_URL = '/api/digital-twin'
export const API_DIGITAL_TWIN_RESET_URL = '/api/digital-twin/reset'
export const API_DIGITAL_TWIN_DEPLOY_URL = '/api/digital-twin/deploy'
export const API_DIGITAL_TWIN_STOP_URL = '/api/digital-twin/stop'
export const API_DIGITAL_TWIN_STATUS_URL = '/api/digital-twin/status'
export const API_DIGITAL_TWIN_VALIDATE_URL = '/api/digital-twin/validate'
export const API_DT_EXEC_URL = '/api/dt-exec'
export const API_DT_EXEC_RUN_URL = '/api/dt-exec/run'
export const API_DT_LOGS_URL = '/api/dt-logs'
export const API_DT_LOGS_FETCH_URL = '/api/dt-logs/fetch'
export const PYTHON_RESOURCE = 'python'
export const API_DT_PYTHON_URL = '/api/dt-python'
export const API_DT_PYTHON_RUN_URL = '/api/dt-python/run'
export const API_DT_PYTHON_START_URL = '/api/dt-python/start'
export const API_DT_PYTHON_STOP_URL = '/api/dt-python/stop'
export const DEFAULT_MODEL_NAME = 'gemini-3.1-pro-preview'
export const AGENTS_RESOURCE = 'agents'
export const API_AGENTS_REPORT_STEP_URL = '/api/agents/report/step'
export const API_AGENTS_REPORT_TOOL_URL = '/api/agents/report/tool'
export const API_AGENTS_REPORT_PROMPT_URL = '/api/agents/report/prompt'
export const API_AGENTS_PLAN_VERIFIER_STEP_URL = '/api/agents/plan-verifier/step'
export const API_AGENTS_PLAN_VERIFIER_TOOL_URL = '/api/agents/plan-verifier/tool'
export const API_AGENTS_PLAN_VERIFIER_PROMPT_URL = '/api/agents/plan-verifier/prompt'
export const API_AGENTS_CODE_STEP_URL = '/api/agents/code/step'
export const API_AGENTS_CODE_TOOL_URL = '/api/agents/code/tool'
export const API_AGENTS_CODE_PROMPT_URL = '/api/agents/code/prompt'
export const API_AGENTS_CODE_REVIEW_STEP_URL = '/api/agents/code-review/step'
export const API_AGENTS_CODE_REVIEW_TOOL_URL = '/api/agents/code-review/tool'
export const API_AGENTS_CODE_REVIEW_PROMPT_URL = '/api/agents/code-review/prompt'
export const API_AGENTS_PLANNER_STEP_URL = '/api/agents/planner/step'
export const API_AGENTS_PLANNER_TOOL_URL = '/api/agents/planner/tool'
export const API_AGENTS_PLANNER_PROMPT_URL = '/api/agents/planner/prompt'
export const API_AGENTS_CODE_MANAGER_STEP_URL = '/api/agents/code-manager/step'
export const API_AGENTS_CODE_MANAGER_TOOL_URL = '/api/agents/code-manager/tool'
export const API_AGENTS_CODE_MANAGER_PROMPT_URL = '/api/agents/code-manager/prompt'
export const API_AGENTS_PLAN_MANAGER_STEP_URL = '/api/agents/plan-manager/step'
export const API_AGENTS_PLAN_MANAGER_TOOL_URL = '/api/agents/plan-manager/tool'
export const API_AGENTS_PLAN_MANAGER_PROMPT_URL = '/api/agents/plan-manager/prompt'
export const API_AGENTS_REPORT_REVIEW_STEP_URL = '/api/agents/report-review/step'
export const API_AGENTS_REPORT_REVIEW_TOOL_URL = '/api/agents/report-review/tool'
export const API_AGENTS_REPORT_REVIEW_PROMPT_URL = '/api/agents/report-review/prompt'
export const API_AGENTS_REPORT_MANAGER_STEP_URL = '/api/agents/report-manager/step'
export const API_AGENTS_REPORT_MANAGER_TOOL_URL = '/api/agents/report-manager/tool'
export const API_AGENTS_REPORT_MANAGER_PROMPT_URL = '/api/agents/report-manager/prompt'
export const API_AGENTS_ORCHESTRATOR_STEP_URL = '/api/agents/orchestrator/step'
export const API_AGENTS_ORCHESTRATOR_TOOL_URL = '/api/agents/orchestrator/tool'
export const API_AGENTS_ORCHESTRATOR_PROMPT_URL = '/api/agents/orchestrator/prompt'
export const API_AGENTS_ATTACK_PATH_VERIFIER_STEP_URL = '/api/agents/attack-path-verifier/step'
export const API_AGENTS_ATTACK_PATH_VERIFIER_TOOL_URL = '/api/agents/attack-path-verifier/tool'
export const API_AGENTS_ATTACK_PATH_VERIFIER_PROMPT_URL = '/api/agents/attack-path-verifier/prompt'
export const API_AGENTS_HOST_ANALYZER_STEP_URL = '/api/agents/host-analyzer/step'
export const API_AGENTS_HOST_ANALYZER_TOOL_URL = '/api/agents/host-analyzer/tool'
export const API_AGENTS_HOST_ANALYZER_PROMPT_URL = '/api/agents/host-analyzer/prompt'
export const API_AGENTS_ACTION_VERIFIER_STEP_URL = '/api/agents/action-verifier/step'
export const API_AGENTS_ACTION_VERIFIER_TOOL_URL = '/api/agents/action-verifier/tool'
export const API_AGENTS_ACTION_VERIFIER_PROMPT_URL = '/api/agents/action-verifier/prompt'
export const API_AGENTS_REPORTS_URL = '/api/agents/reports'
export const API_AGENTS_SESSIONS_ACTIVE_URL = '/api/agents/sessions/active'
export const API_AGENTS_SESSIONS_URL = '/api/agents/sessions'
export const API_AGENTS_JOBS_URL = '/api/agents/jobs'
export const apiJobEventsUrl = (jobId) => `/api/agents/jobs/${jobId}/events`
export const apiJobCancelUrl = (jobId) => `/api/agents/jobs/${jobId}/cancel`
export const apiJobStatusUrl = (jobId) => `/api/agents/jobs/${jobId}/status`
export const API_EXAMPLES_URL = '/api/examples'
export const API_DIGITAL_TWIN_CONFIGS_URL = '/api/digital-twin/configs'
export const apiDigitalTwinConfigDeployUrl = (id) => `/api/digital-twin/configs/${id}/deploy`
export const apiDigitalTwinConfigStopUrl = (id) => `/api/digital-twin/configs/${id}/stop`
export const apiDigitalTwinConfigStatusUrl = (id) => `/api/digital-twin/configs/${id}/status`
export const apiDigitalTwinConfigValidateUrl = (id) => `/api/digital-twin/configs/${id}/validate`
export const apiDigitalTwinConfigValidationResultsUrl = (id) =>
  `/api/digital-twin/configs/${id}/validation-results`
export const apiSessionsActiveUrl = (agentType) =>
  agentType
    ? `${API_AGENTS_SESSIONS_ACTIVE_URL}?agent_type=${agentType}`
    : API_AGENTS_SESSIONS_ACTIVE_URL
