/**
 * File with constants
 */

export const LOGIN_RESOURCE = 'login'
export const ABOUT_RESOURCE = 'about'
export const RESPONSE_PLANNER_RESOURCE = 'response-planner'
export const LLM_RESOURCE = 'llm'
export const NOT_FOUND_RESOURCE = '*'
export const API_BASE_URL = '/api'
export const API_HEALTH_URL = '/api/health'
export const API_PLAN_URL = '/api/plan'
export const API_EXAMPLE_URL = '/api/example'
export const API_LOGIN_URL = '/api/login'
export const API_LLM_URL = '/api/llm'
export const TOOLS_RESOURCE = 'tools'
export const API_TAVILY_URL = '/api/tavily'
export const API_TAVILY_SEARCH_URL = '/api/tavily/search'
export const API_NVD_URL = '/api/nvd'
export const API_NVD_SEARCH_URL = '/api/nvd/search'
export const API_MITRE_URL = '/api/mitre'
export const API_MITRE_SEARCH_URL = '/api/mitre/search'
export const API_VIRUSTOTAL_URL = '/api/virustotal'
export const API_VIRUSTOTAL_SCAN_URL = '/api/virustotal/scan'
export const API_ABUSEIPDB_URL = '/api/abuseipdb'
export const API_ABUSEIPDB_CHECK_URL = '/api/abuseipdb/check'
export const API_OTX_URL = '/api/otx'
export const API_OTX_SEARCH_URL = '/api/otx/search'
export const DIGITAL_TWIN_RESOURCE = 'digital-twin'
export const API_DIGITAL_TWIN_URL = '/api/digital-twin'
export const API_DIGITAL_TWIN_RESET_URL = '/api/digital-twin/reset'
export const API_DIGITAL_TWIN_DEPLOY_URL = '/api/digital-twin/deploy'
export const API_DIGITAL_TWIN_STOP_URL = '/api/digital-twin/stop'
export const API_DIGITAL_TWIN_STATUS_URL = '/api/digital-twin/status'
export const API_DIGITAL_TWIN_VALIDATE_URL = '/api/digital-twin/validate'
export const API_DT_EXEC_URL = '/api/dt-exec'
export const API_DT_EXEC_RUN_URL = '/api/dt-exec/run'
export const API_DT_LOGS_URL = '/api/dt-logs'
export const API_DT_LOGS_FETCH_URL = '/api/dt-logs/fetch'
export const API_DT_PYTHON_URL = '/api/dt-python'
export const API_DT_PYTHON_RUN_URL = '/api/dt-python/run'
