import ImageThumbnails from './shared/ImageThumbnails.jsx'
import PromptModal from './shared/PromptModal.jsx'
import ExampleSelector from './shared/ExampleSelector.jsx'

/**
 * Configuration tab for the Code Reviewer Agent.
 */
function CodeReviewerConfigTab({
  systemDescription,
  setSystemDescription,
  incidentReport,
  setIncidentReport,
  specification,
  setSpecification,
  operatorFeedback,
  setOperatorFeedback,
  codeReport,
  setCodeReport,
  systemDescriptionImages,
  setSystemDescriptionImages,
  incidentReportImages,
  setIncidentReportImages,
  handlePaste,
  isAgentBusy,
  handleRun,
  loadExample,
  handleClear,
  fetchPrompt,
  loadingPrompt,
  models,
  selectedModel,
  setSelectedModel,
  autopilot,
  setAutopilot,
  showPromptModal,
  promptText,
  promptImages,
  setShowPromptModal
}) {
  return (
    <div style={{ marginTop: '16px' }}>
      <div className="ia-description">
        <p>
          This agent reviews a Gymnasium MDP environment generated by the Code Agent. It analyzes
          the code against the incident context and produces a structured review identifying missing
          actions, inconsistent transitions, wrong commands, and missed recovery options.
          <ol>
            <li>
              Analyze the MDP code for completeness, transition realism, and command correctness.
            </li>
            <li>Test the MDP in a sandbox and verify commands on the digital twin.</li>
            <li>Produce a structured review report with findings and recommendations.</li>
          </ol>
        </p>
      </div>

      <div className="ia-section">
        <label htmlFor="cr-system-desc">System description</label>
        <p className="ia-hint">
          Describe the target system, its architecture, hosts, and services.
        </p>
        <textarea
          id="cr-system-desc"
          className="form-control ia-textarea"
          rows="6"
          value={systemDescription}
          onChange={(e) => setSystemDescription(e.target.value)}
          onPaste={handlePaste}
          disabled={isAgentBusy}
          placeholder="e.g., The system consists of a web server, database server, and firewall..."
        />
        <ImageThumbnails
          images={systemDescriptionImages}
          setImages={setSystemDescriptionImages}
          disabled={isAgentBusy}
        />
      </div>
      <div className="ia-section">
        <label htmlFor="cr-incident-report">Incident report</label>
        <p className="ia-hint">
          Paste the incident report/assessment produced by the Information Agent.
        </p>
        <textarea
          id="cr-incident-report"
          className="form-control ia-textarea"
          rows="6"
          value={incidentReport}
          onChange={(e) => setIncidentReport(e.target.value)}
          disabled={isAgentBusy}
          placeholder="e.g., An SSH brute-force attack was detected on server 3..."
        />
        <ImageThumbnails
          images={incidentReportImages}
          setImages={setIncidentReportImages}
          disabled={isAgentBusy}
        />
      </div>
      <div className="ia-section">
        <label htmlFor="cr-specification">Specification commands</label>
        <p className="ia-hint">
          JSON array of specification commands that define service-level requirements of the system.
        </p>
        <textarea
          id="cr-specification"
          className="form-control ia-textarea"
          rows="4"
          value={specification}
          onChange={(e) => setSpecification(e.target.value)}
          disabled={isAgentBusy}
          placeholder="Leave empty to use default specification commands from the digital twin config."
        />
      </div>
      <div className="ia-section">
        <label htmlFor="cr-operator-feedback">Operator feedback (optional)</label>
        <p className="ia-hint">Additional guidance or constraints for the review.</p>
        <textarea
          id="cr-operator-feedback"
          className="form-control ia-textarea"
          rows="4"
          value={operatorFeedback}
          onChange={(e) => setOperatorFeedback(e.target.value)}
          disabled={isAgentBusy}
          placeholder="e.g., Pay special attention to containment actions and firewall rules."
        />
      </div>
      <div className="ia-section">
        <label htmlFor="cr-code-report">Code Agent report</label>
        <p className="ia-hint">Paste the JSON code report produced by the Code Agent.</p>
        <textarea
          id="cr-code-report"
          className="form-control ia-textarea"
          rows="12"
          value={codeReport}
          onChange={(e) => setCodeReport(e.target.value)}
          disabled={isAgentBusy}
          placeholder='{"executive_summary": "...", "generated_code": "...", "actions": [...], ...}'
          style={{ fontFamily: 'monospace', fontSize: '12px' }}
        />
      </div>
      <button
        type="button"
        className="btn btn-dark btn-sm ia-btn"
        onClick={handleRun}
        disabled={isAgentBusy || !codeReport}
      >
        <i className="fa fa-bolt" aria-hidden="true" />
        {isAgentBusy ? ' Running...' : ' Run agent'}
      </button>
      <ExampleSelector onLoad={loadExample} disabled={isAgentBusy} />
      <button
        type="button"
        className="btn btn-outline-secondary btn-sm ia-btn"
        onClick={handleClear}
        disabled={isAgentBusy}
      >
        <i className="fa fa-eraser" aria-hidden="true" /> Clear all
      </button>
      <button
        type="button"
        className="btn btn-outline-dark btn-sm ia-btn"
        onClick={fetchPrompt}
        disabled={loadingPrompt}
      >
        <i className="fa fa-file-text-o" aria-hidden="true" />{' '}
        {loadingPrompt ? 'Loading...' : 'Show prompt'}
      </button>
      <span className="ia-model-label">LLM:</span>
      <select
        className="form-control form-control-sm ia-model-select"
        value={selectedModel}
        onChange={(e) => setSelectedModel(e.target.value)}
        disabled={isAgentBusy}
      >
        <option value="">Default (Gemini 3 Pro)</option>
        {models.map((m) => (
          <option key={m.name} value={m.name}>
            {m.display_name}
          </option>
        ))}
      </select>
      <div className="form-check form-check-inline ia-btn">
        <input
          className="form-check-input"
          type="checkbox"
          id="cr-autopilot"
          checked={autopilot}
          onChange={(e) => setAutopilot(e.target.checked)}
        />
        <label className="form-check-label" htmlFor="cr-autopilot">
          Autopilot <span className="ia-hint">(auto-approve all tool requests)</span>
        </label>
      </div>

      <PromptModal
        show={showPromptModal}
        promptText={promptText}
        promptImages={promptImages}
        onClose={() => setShowPromptModal(false)}
      />
    </div>
  )
}

export default CodeReviewerConfigTab
