import ImageThumbnails from './shared/ImageThumbnails.jsx'
import ExampleSelector from './shared/ExampleSelector.jsx'

/**
 * Configuration tab for the DP Agent.
 */
function DpAgentConfigTab({
  systemDescription,
  setSystemDescription,
  incidentReport,
  setIncidentReport,
  specification,
  setSpecification,
  operatorFeedback,
  setOperatorFeedback,
  codeReport,
  setCodeReport,
  systemDescriptionImages,
  setSystemDescriptionImages,
  incidentReportImages,
  setIncidentReportImages,
  handlePaste,
  isAgentBusy,
  handleRun,
  loadExample,
  handleClear,
  autopilot,
  setAutopilot
}) {
  return (
    <div style={{ marginTop: '16px' }}>
      <div className="ia-description">
        <p>
          This agent solves a Gymnasium MDP environment (generated by the Code Agent) using dynamic
          programming (value iteration). It discretizes the state space, builds a transition model,
          and computes the optimal policy to produce an actionable incident response plan.
          <ol>
            <li>Analyze the MDP code to understand state space, actions, and transitions.</li>
            <li>Solve the MDP with value iteration and live convergence streaming.</li>
            <li>Evaluate the optimal policy and produce a structured incident response plan.</li>
          </ol>
        </p>
      </div>

      <div className="ia-section">
        <label htmlFor="dp-system-desc">System description</label>
        <p className="ia-hint">
          Describe the target system, its architecture, hosts, and services.
        </p>
        <textarea
          id="dp-system-desc"
          className="form-control ia-textarea"
          rows="6"
          value={systemDescription}
          onChange={(e) => setSystemDescription(e.target.value)}
          onPaste={handlePaste}
          disabled={isAgentBusy}
          placeholder="e.g., The system consists of a web server, database server, and firewall..."
        />
        <ImageThumbnails
          images={systemDescriptionImages}
          setImages={setSystemDescriptionImages}
          disabled={isAgentBusy}
        />
      </div>
      <div className="ia-section">
        <label htmlFor="dp-incident-report">Incident report</label>
        <p className="ia-hint">
          Paste the incident report/assessment produced by the Information Agent.
        </p>
        <textarea
          id="dp-incident-report"
          className="form-control ia-textarea"
          rows="6"
          value={incidentReport}
          onChange={(e) => setIncidentReport(e.target.value)}
          disabled={isAgentBusy}
          placeholder="e.g., An SSH brute-force attack was detected on server 3..."
        />
        <ImageThumbnails
          images={incidentReportImages}
          setImages={setIncidentReportImages}
          disabled={isAgentBusy}
        />
      </div>
      <div className="ia-section">
        <label htmlFor="dp-specification">Specification commands</label>
        <p className="ia-hint">
          JSON array of specification commands that define service-level requirements of the target
          system.
        </p>
        <textarea
          id="dp-specification"
          className="form-control ia-textarea"
          rows="4"
          value={specification}
          onChange={(e) => setSpecification(e.target.value)}
          disabled={isAgentBusy}
          placeholder="Leave empty to use default specification commands from the digital twin config."
        />
      </div>
      <div className="ia-section">
        <label htmlFor="dp-operator-feedback">Operator feedback (optional)</label>
        <p className="ia-hint">Additional guidance or constraints for the planner.</p>
        <textarea
          id="dp-operator-feedback"
          className="form-control ia-textarea"
          rows="4"
          value={operatorFeedback}
          onChange={(e) => setOperatorFeedback(e.target.value)}
          disabled={isAgentBusy}
          placeholder="e.g., Prioritize containment actions and minimize service downtime."
        />
      </div>
      <div className="ia-section">
        <label htmlFor="dp-code-report">Code Agent report</label>
        <p className="ia-hint">Paste the JSON code report produced by the Code Agent.</p>
        <textarea
          id="dp-code-report"
          className="form-control ia-textarea"
          rows="12"
          value={codeReport}
          onChange={(e) => setCodeReport(e.target.value)}
          disabled={isAgentBusy}
          placeholder='{"executive_summary": "...", "generated_code": "...", "actions": [...], ...}'
          style={{ fontFamily: 'monospace', fontSize: '12px' }}
        />
      </div>
      <button
        type="button"
        className="btn btn-dark btn-sm ia-btn"
        onClick={handleRun}
        disabled={isAgentBusy || !codeReport}
      >
        <i className="fa fa-bolt" aria-hidden="true" />
        {isAgentBusy ? ' Running...' : ' Run agent'}
      </button>
      <ExampleSelector onLoad={loadExample} disabled={isAgentBusy} />
      <button
        type="button"
        className="btn btn-outline-secondary btn-sm ia-btn"
        onClick={handleClear}
        disabled={isAgentBusy}
      >
        <i className="fa fa-eraser" aria-hidden="true" /> Clear all
      </button>
      <div className="form-check form-check-inline ia-btn">
        <input
          className="form-check-input"
          type="checkbox"
          id="dp-autopilot"
          checked={autopilot}
          onChange={(e) => setAutopilot(e.target.checked)}
        />
        <label className="form-check-label" htmlFor="dp-autopilot">
          Autopilot <span className="ia-hint">(auto-approve all tool requests)</span>
        </label>
      </div>
    </div>
  )
}

export default DpAgentConfigTab
